# Generated by Django 3.1.3 on 2020-11-14 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201114_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 19, 30, 8, 240407, tzinfo=utc)),
        ),
    ]
