# Generated by Django 3.1.3 on 2020-11-15 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201114_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 10, 54, 35, 944868, tzinfo=utc)),
        ),
    ]
