# Generated by Django 3.1.3 on 2020-11-15 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201115_0555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 10, 58, 23, 621209, tzinfo=utc)),
        ),
    ]
