# Generated by Django 3.1.3 on 2020-11-14 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2020, 11, 14, 18, 33, 26, 412855, tzinfo=utc))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2020, 11, 14, 18, 33, 26, 412880, tzinfo=utc))),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
