# Generated by Django 3.1.3 on 2020-11-14 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0002_auto_20201114_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='account_id',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 19, 30, 8, 258504, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 19, 30, 8, 258485, tzinfo=utc)),
        ),
    ]
