# Generated by Django 3.1.3 on 2020-11-15 00:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0003_auto_20201114_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 0, 1, 52, 919830, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 0, 1, 52, 919810, tzinfo=utc)),
        ),
    ]
