# Generated by Django 3.1.3 on 2020-11-15 04:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0004_auto_20201114_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 4, 21, 48, 275971, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 4, 21, 48, 275952, tzinfo=utc)),
        ),
    ]
