# Generated by Django 3.1.3 on 2020-11-15 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0005_auto_20201114_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 10, 54, 35, 993174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 10, 54, 35, 993155, tzinfo=utc)),
        ),
    ]
