# Generated by Django 3.1.3 on 2020-11-15 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_calendar', '0008_auto_20201115_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 11, 23, 18, 20438, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 11, 23, 18, 20420, tzinfo=utc)),
        ),
    ]
